{"version":3,"sources":["throw.es6"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;AAAA;;;AAGA,QAAI,+BAAI,SAAJ,CAAI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;;AAAA;AAAA;AAAA;;AAAA;AAAA;AAAA;;AAIA,gCAAQ,GAAR,CAAY,MAAZ;;AAJA;AAAA;AAAA;AAAA;AAAA;AAAA,WAAJ,CAAI;AAAA,KAAJ,CAAJ;;AAQA,QAAI,IAAI,GAAR;AACA,MAAE,IAAF;;AAEA,QAAI;AACA,UAAE,KAAF,CAAQ,IAAI,KAAJ,CAAU,GAAV,CAAR;AACA,UAAE,KAAF,CAAQ,IAAI,KAAJ,CAAU,GAAV,CAAR;AACH,KAHD,CAGE,OAAO,CAAP,EAAU;AACR,gBAAQ,GAAR,CAAY,MAAZ,EAAoB,CAApB;AACH;AACD;AACA","file":"throw.js","sourcesContent":["/**\r\n * throw方法可以接受一个参数，该参数会被catch语句接收，建议抛出Error对象的实例。\r\n */\r\nvar g = function* () {\r\n    try {\r\n        yield;\r\n    } catch (e) {\r\n        console.log('内部捕获', e);\r\n    }\r\n};\r\n\r\nvar i = g();\r\ni.next();\r\n\r\ntry {\r\n    i.throw(new Error('a'));\r\n    i.throw(new Error('b'));\r\n} catch (e) {\r\n    console.log('外部捕获', e);\r\n}\r\n// 内部捕获 a\r\n// 外部捕获 b"]}